Books app project: Add and delete feature
AFakhriddinov/Books-app pull request #1
Opened 2023-03-27 20:23 UTC by AFakhriddinov

**In this milestone,** 
Created a new repository
Built books app with add and remove functionality
The app is built simple HTML, CSS and JavaScript
Set up linters for HTML CSS, and JavaScript

2023-03-27 21:40 UTC, AdnanOlarmmi requested changes
Hi @AFakhriddinov, 

This is Adnan Is-haq, your beloved code reviewer,

You've done a very good job so far, but a few things still need to be worked on before moving on to the next project, but you're so close!

![You're Almost there, funny one eyed alien](https://user-images.githubusercontent.com/41163571/217957948-6d8d9f33-125c-4724-954f-330eed60533c.gif)

## Highlights
- Professional Readme.
- Nice UI design.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-27 21:40 UTC, AdnanOlarmmi commented on javascript.js
> +  if (title.value !== '' && author.value !== '') {
- [ ] To follow JavaScript best practices please kindly note that `null` is also a `false` value. 

You could write it like this.
```
if(title.value && author.value)
```

meaning if title.value and author.value is true (it's not null) execute the code.

2023-03-27 21:40 UTC, AdnanOlarmmi commented on javascript.js
- [ ] Kindly note that from the project requirements is the persistence of the data in the `local storage`.

![mobile](https://user-images.githubusercontent.com/41163571/228068265-3a1166fc-721c-4c83-85cd-46301f964418.gif)

You can use [this](https://www.youtube.com/watch?v=k8yJCeuP6I8), or [this](https://www.youtube.com/watch?v=AUOzvFzdIk4) or [this](https://www.youtube.com/watch?v=fYTTUBa-lPc) to learn more.

2023-03-27 21:40 UTC, AdnanOlarmmi commented on index.html
> +      <br />
- [ ] [OPTIONAL] Kindly use the `form` tag for the form. This will open many opportunities for you for example enabling the `enter` button for submission and likewise using form.reset() to clear out the values from the `input` boxes, you might need to use event.preventDefault(); to prevent the page from loading, check [this link](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault) for more.

Check this [stack overflow](https://stackoverflow.com/questions/21222457/when-should-i-use-forms-over-standard-div#:~:text=They%20have%20completely%20different%20purposes,organization%20or%20stylization%2C%20divs%20should) thread for more.

2023-03-28 17:22 UTC, ishimwezachee approved these changes
Hi @AFakhriddinov  and @DianaBeki,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![image](https://user-images.githubusercontent.com/43877689/228318709-47fe38b7-a40a-4cdf-9055-2f26f0ea225c.png)

## Highlights
All linters are passing ✔️
Correct use of GitFlow ✔️
Project is running successfully ✔️
Implemented the changes from the previous reviewer ✔️


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-28 17:47 UTC, merged